name: flutter_amiibo_responsive
description: Create app connect with amiibo API and set responsive

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.8.0 <4.0.0"
  flutter: 3.32.0

dependencies:
  collection: ^1.19.0
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_hooks: ^0.21.2
  flutter_web_plugins:
    sdk: flutter
  gap: ^3.0.1
  google_fonts: ^6.2.1
  http: ^1.4.0
  intl: ^0.20.2
  json_annotation: ^4.9.0
  shimmer_animation: ^2.2.2
  window_size:
    git:
      url: https://github.com/google/flutter-desktop-embedding.git
      path: plugins/window_size

dev_dependencies:
  bloc_test: ^10.0.0
  build_runner: ^2.5.4
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.6
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  json_serializable: ^6.10.0
  mocktail: ^1.0.4
  mocktail_image_network: ^1.2.0
  remove_from_coverage: ^2.0.0
  very_good_analysis: ^9.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito-Regular.ttf
