name: flutter_amiibo_responsive
description: Create app connect with amiibo API and set responsive

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: 3.3.10

dependencies:
  collection: ^1.16.0
  cupertino_icons: ^1.0.5
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  freezed_annotation: ^2.2.0
  google_fonts: ^3.0.1
  http: ^0.13.5
  intl: ^0.18.0
  json_annotation: ^4.7.0
  shimmer_animation: ^2.1.0+1
  window_size:
    git:
      url: https://github.com/google/flutter-desktop-embedding.git
      path: plugins/window_size

dev_dependencies:
  bloc_test: ^9.1.0
  build_runner: ^2.3.0
  flutter_test:
    sdk: flutter
  freezed: ^2.2.0
  integration_test:
    sdk: flutter
  json_serializable: ^6.5.4
  mocktail: ^0.3.0
  network_image_mock: ^2.1.1
  remove_from_coverage: ^2.0.0
  very_good_analysis: ^3.1.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
