name: flutter_amiibo_responsive
description: Create app connect with amiibo API and set responsive

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <3.0.0"
  flutter: 3.7.0

dependencies:
  collection: ^1.17.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_hooks: ^0.18.6
  freezed_annotation: ^2.2.0
  google_fonts: ^4.0.4
  http: ^0.13.5
  intl: ^0.18.0
  json_annotation: ^4.8.0
  shimmer_animation: ^2.1.0+1
  window_size:
    git:
      url: https://github.com/google/flutter-desktop-embedding.git
      path: plugins/window_size

dev_dependencies:
  bloc_test: ^9.1.1
  build_runner: ^2.3.3
  flutter_test:
    sdk: flutter
  freezed: ^2.3.2
  integration_test:
    sdk: flutter
  json_serializable: ^6.6.1
  mocktail: ^0.3.0
  mocktail_image_network: ^0.3.1
  remove_from_coverage: ^2.0.0
  very_good_analysis: ^4.0.0+1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
