name: flutter_amiibo_responsive
description: Create app connect with amiibo API and set responsive

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: 3.19.0

dependencies:
  collection: ^1.18.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  flutter_hooks: ^0.20.5
  google_fonts: ^6.2.1
  http: ^1.2.0
  intl: ^0.19.0
  json_annotation: ^4.9.0
  shimmer_animation: ^2.1.0+1
  uni_links: ^0.5.1
  window_size:
    git:
      url: https://github.com/google/flutter-desktop-embedding.git
      path: plugins/window_size

dev_dependencies:
  bloc_test: ^9.1.7
  build_runner: ^2.4.10
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  json_serializable: ^6.8.0
  mocktail: ^1.0.3
  mocktail_image_network: ^1.1.0
  remove_from_coverage: ^2.0.0
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
